#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
set -eu
cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

sysname=$(uname -s)
pkg_config=${PKG_CONFIG:-pkg-config}
case "$sysname" in
    MINGW*|MSYS*)
        if [ -z "${PKG_CONFIG:-}" ] && command -v x86_64-w64-mingw32-pkg-config >/dev/null 2>&1; then
            pkg_config=x86_64-w64-mingw32-pkg-config
        fi ;;
esac
command -v "$pkg_config" >/dev/null 2>&1 || fail "$pkg_config is required"

package=
for candidate in opencv5 opencv4 opencv; do
    if "$pkg_config" --exists "$candidate"; then package=$candidate; break; fi
done
if [ -z "$package" ] && [ "$sysname" = Darwin ] && command -v port >/dev/null 2>&1; then
    prefix=$(dirname "$(dirname "$(command -v port)")")
    export PKG_CONFIG_PATH="$prefix/lib/opencv4/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
    for candidate in opencv5 opencv4 opencv; do
        if "$pkg_config" --exists "$candidate"; then package=$candidate; break; fi
    done
fi
[ -n "$package" ] || fail 'OpenCV pkg-config metadata not found (opencv5, opencv4, opencv)'

version=$("$pkg_config" --modversion "$package")
printf '%s\n' "$version" | grep -Eq '^(4\.[1-9][0-9]*\.[0-9]+|5\.0\.[0-9]+)$' ||
    fail "OpenCV $version is outside the bootstrap target range (4.1-4.x, 5.0.x)"
header=opencv2/video/tracking.hpp
backend=video

include_dir=$("$pkg_config" --variable=includedir "$package")
[ -n "$include_dir" ] || include_dir=$("$pkg_config" --variable=includedir_new "$package")
library_dir=$("$pkg_config" --variable=libdir "$package")
[ -n "$include_dir" ] && [ -n "$library_dir" ] || fail 'OpenCV metadata lacks include/lib directories'
[ -f "$include_dir/$header" ] || fail "Missing native header $header"
case "$sysname" in
    Darwin) native_library="$library_dir/libopencv_video.dylib" ;;
    MINGW*|MSYS*) native_library="$library_dir/libopencv_video.dll.a" ;;
    *) native_library="$library_dir/libopencv_video.so"
       [ -f "$native_library" ] || native_library="$library_dir/libopencv_video.a" ;;
esac
[ -f "$native_library" ] || fail "Missing native backend library $native_library"

core_prefix=${OPENCV_CORE_ALIRE_PREFIX:-}
[ -n "$core_prefix" ] || fail 'Use alr build (or set OPENCV_CORE_ALIRE_PREFIX to the resolved Core crate/install)'
bridge_dir=
for candidate in "$core_prefix/include" "$core_prefix/cpp"; do
    if [ -f "$candidate/opencv_core_module_bridge.hpp" ]; then bridge_dir=$candidate; break; fi
done
[ -n "$bridge_dir" ] || fail "Core bridge header is missing under $core_prefix/include or /cpp"

shim_build=Static_PIC
cxx_toolchain=GNU
cxx_driver=g++
cxx_sysroot=
cxx_runtime=-lstdc++
video_link=-lopencv_video
core_link=-lopencv_core
core_shim_link=

if [ "$sysname" = Darwin ]; then
    shim_build=Relocatable
    cxx_toolchain=Apple_Clang
    cxx_runtime=-lc++
    command -v xcrun >/dev/null 2>&1 || fail 'Apple xcrun is required on macOS'
    cxx_driver=$(xcrun --find clang++)
    cxx_sysroot=$(xcrun --sdk macosx --show-sdk-path)
    [ -n "$cxx_driver" ] && [ -n "$cxx_sysroot" ] || fail 'Apple compiler/SDK lookup failed'
fi

case "$sysname" in
    MINGW*|MSYS*)
        shim_build=External_Relocatable
        video_link="$library_dir/libopencv_video.dll.a"
        core_link="$library_dir/libopencv_core.dll.a"
        core_shim_link="$core_prefix/lib/libopencv_core_shim.dll.a"
        mingw_prefix=$(dirname "$library_dir")
        cxx_driver="$mingw_prefix/bin/g++.exe"
        [ -f "$cxx_driver" ] || cxx_driver="$mingw_prefix/bin/g++"
        for file in "$video_link" "$core_link" "$core_shim_link" "$cxx_driver"; do
            [ -f "$file" ] || fail "Missing Windows build input: $file"
        done
        case "$cxx_driver" in *gnat_native*) fail 'Do not compile the shim with GNAT g++' ;; esac
        command -v cygpath >/dev/null 2>&1 || fail 'cygpath is required on MSYS2'
        include_dir=$(cygpath -m "$include_dir")
        library_dir=$(cygpath -m "$library_dir")
        bridge_dir=$(cygpath -m "$bridge_dir")
        video_link=$(cygpath -m "$video_link")
        core_link=$(cygpath -m "$core_link")
        core_shim_link=$(cygpath -m "$core_shim_link")
        cxx_driver=$(cygpath -m "$cxx_driver") ;;
esac

case "$include_dir$library_dir$bridge_dir$cxx_driver$cxx_sysroot$video_link$core_link$core_shim_link" in
    *\"*) fail 'Double quotes in build paths are unsupported' ;;
esac

mkdir -p config
output=config/opencv_video_install.gpr
temporary="$output.tmp"
trap 'rm -f "$temporary"' EXIT HUP INT TERM
cat > "$temporary" <<EOF_GPR
-- Generated by scripts/configure_opencv.sh; do not commit.
abstract project OpenCV_Video_Install is
   type Shim_Build_Kind is ("Static_PIC", "Relocatable", "External_Relocatable");
   type Cxx_Toolchain_Kind is ("GNU", "Apple_Clang");
   Shim_Build : Shim_Build_Kind := "$shim_build";
   Cxx_Toolchain : Cxx_Toolchain_Kind := "$cxx_toolchain";
   Native_Version := "$version";
   Native_Backend := "$backend";
   Native_Header := "$header";
   Include_Switch := "-I$include_dir";
   Core_Bridge_Include_Switch := "-I$bridge_dir";
   Library_Search_Switch := "-L$library_dir";
   OpenCV_Video_Link_Option := "$video_link";
   OpenCV_Core_Link_Option := "$core_link";
   Core_Shim_Link_Option := "$core_shim_link";
   Cxx_Runtime_Switch := "$cxx_runtime";
   Cxx_Driver := "$cxx_driver";
   Cxx_Sysroot := "$cxx_sysroot";
end OpenCV_Video_Install;
EOF_GPR

sh scripts/build_opencv_shim.sh "$shim_build" "$cxx_driver" "$include_dir" \
    "$bridge_dir" "$video_link" "$core_link" "$core_shim_link"
mv "$temporary" "$output"
printf 'OpenCV: %s (%s), native video backend: %s\nCore bridge: %s\nShim: %s\n' \
    "$version" "$package" "$backend" "$bridge_dir" "$shim_build"
